load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "io_bazel_rules_dotnet",
    remote = "https://github.com/bazelbuild/rules_dotnet",
    tag = "0.0.4",
)

load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "core_register_sdk", "dotnet_register_toolchains", "dotnet_repositories", "net_register_sdk", "nuget_package")

dotnet_register_toolchains()

dotnet_repositories()

core_register_sdk(
    "v2.1.502",
    name = "core_sdk",
)

net_register_sdk(
    "net472",
    name = "net_sdk",
    tools_version = "net472",
)

### Generated by the tool
nuget_package(
    name = "microsoft.crmsdk.coreassemblies",
    package = "microsoft.crmsdk.coreassemblies",
    version = "9.0.2.24",
    sha256 = "99d32553c1a2c25cbc784e772ce6cef5f05eae56cbd5ce82aa41e934ea161943",
    net_lib = {
        "net462": "lib/net462/Microsoft.Xrm.Sdk.dll",
        "net47": "lib/net462/Microsoft.Xrm.Sdk.dll",
        "net471": "lib/net462/Microsoft.Xrm.Sdk.dll",
        "net472": "lib/net462/Microsoft.Xrm.Sdk.dll",
    },
    mono_lib = "lib/net462/Microsoft.Crm.Sdk.Proxy.dll",
    net_files = {
        "net462": [
           "lib/net462/LicenseTerms.docx",
           "lib/net462/Microsoft.Crm.Sdk.Proxy.dll",
           "lib/net462/Microsoft.Crm.Sdk.Proxy.xml",
           "lib/net462/Microsoft.Xrm.Sdk.dll",
           "lib/net462/Microsoft.Xrm.Sdk.xml",
           "lib/net462/Other Redistributable.txt",
           "lib/net462/Third Party Notices for Dynamics 365 SDK.docx",
        ],
        "net47": [
           "lib/net462/LicenseTerms.docx",
           "lib/net462/Microsoft.Crm.Sdk.Proxy.dll",
           "lib/net462/Microsoft.Crm.Sdk.Proxy.xml",
           "lib/net462/Microsoft.Xrm.Sdk.dll",
           "lib/net462/Microsoft.Xrm.Sdk.xml",
           "lib/net462/Other Redistributable.txt",
           "lib/net462/Third Party Notices for Dynamics 365 SDK.docx",
        ],
        "net471": [
           "lib/net462/LicenseTerms.docx",
           "lib/net462/Microsoft.Crm.Sdk.Proxy.dll",
           "lib/net462/Microsoft.Crm.Sdk.Proxy.xml",
           "lib/net462/Microsoft.Xrm.Sdk.dll",
           "lib/net462/Microsoft.Xrm.Sdk.xml",
           "lib/net462/Other Redistributable.txt",
           "lib/net462/Third Party Notices for Dynamics 365 SDK.docx",
        ],
        "net472": [
           "lib/net462/LicenseTerms.docx",
           "lib/net462/Microsoft.Crm.Sdk.Proxy.dll",
           "lib/net462/Microsoft.Crm.Sdk.Proxy.xml",
           "lib/net462/Microsoft.Xrm.Sdk.dll",
           "lib/net462/Microsoft.Xrm.Sdk.xml",
           "lib/net462/Other Redistributable.txt",
           "lib/net462/Third Party Notices for Dynamics 365 SDK.docx",
        ],
    },
    mono_files = [
        "lib/net462/LicenseTerms.docx",
        "lib/net462/Microsoft.Crm.Sdk.Proxy.dll",
        "lib/net462/Microsoft.Crm.Sdk.Proxy.xml",
        "lib/net462/Microsoft.Xrm.Sdk.dll",
        "lib/net462/Microsoft.Xrm.Sdk.xml",
        "lib/net462/Other Redistributable.txt",
        "lib/net462/Third Party Notices for Dynamics 365 SDK.docx",
    ],
)
### End of generated by the tool
