load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "io_bazel_rules_dotnet",
    remote = "https://github.com/bazelbuild/rules_dotnet",
    tag = "0.0.3",
)

load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "dotnet_register_toolchains", "dotnet_repositories", "net_register_sdk")

dotnet_register_toolchains()

dotnet_repositories()

net_register_sdk(
    "net472",
    name = "net_sdk",
    tools_version = "net472",
)
